# -*- coding: utf-8 -*-
"""
Автоматическое исправление известных ошибок, которые вносит unrpyc (ветка
master, нацеленная на Ren'Py 8) при раскомпиляции игр на Ren'Py 7 и ниже.
unrpyc сам честно предупреждает об этом ("this .rpyc file was generated by
ren'py version 7 or below... errors or incorrect decompilation might
occur") — в подавляющем большинстве случаев результат всё равно рабочий,
но иногда проскакивают единичные синтаксические ошибки, из-за которых
Ren'Py SDK падает при генерации файлов перевода (команда "translate"), а
без этого модуля пользователю пришлось бы находить такие места по одной,
вручную, по логу SDK (сам SDK останавливается на первой же ошибке).

Официальная альтернатива — ветка "legacy" самого unrpyc (v1.x), она
специально нацелена на Ren'Py 6/7 и потому точнее для таких игр. Но она
требует ОТДЕЛЬНО установленный Python 2.7 (сам движок Ren'Py 7 работал на
Python 2) — на современной Windows это лишняя гиря, а сама ветка "master",
судя по практике, и так восстанавливает почти всё верно, спотыкаясь лишь
на единичных строках. Поэтому вместо переключения на legacy этот модуль
чинит уже опознанные конкретные поломки после раскомпиляции.

Пока опознаны (по логам пользователя, реальные игры на Ren'Py 7.8.7) два
шаблона:

1) fix_empty_block_colon — инструкция заканчивается двоеточием, как будто
   дальше идёт вложенный блок, но дальше ничего нет (следующая непустая
   строка имеет такой же или меньший отступ). Ren'Py в этом случае падает
   с ошибкой вида "... statement expects a non-empty block". Сам Ren'Py
   никогда не генерирует такую пустую заготовку блока — значит, лишнее
   двоеточие можно смело убрать: хуже точно не станет (сейчас строка
   гарантированно вообще не парсится), а без двоеточия получается тот же
   код, что и должен быть в оригинале.
       "show bg ch7outside1 with fade:"   (дальше блока нет)
    -> "show bg ch7outside1 with fade"

2) fix_dangling_keyword_comment — в экранном языке (screen language)
   именованный аргумент (чаще всего "action") остаётся без значения,
   потому что unrpyc не смог до конца восстановить исходное
   Python-выражение и вставил его как комментарий сразу после ключевого
   слова, не убрав само ключевое слово. Ren'Py падает с "the X keyword
   argument was not given a value". Это исправление МЕНЕЕ гарантированно
   безопасно, чем первое (нельзя быть на 100% уверенным, что
   закомментированное выражение — именно то, что было в оригинале),
   поэтому такие правки дополнительно помечаются в журнале как требующие
   проверки глазами.
       'textbutton _("Next Page") action #[SetVariable(...), ...]'
    -> 'textbutton _("Next Page") action [SetVariable(...), ...]'

Оба правила специально узкие и консервативные — модуль не пытается
угадывать и чинить любой возможный синтаксис Ren'Py, только эти два
конкретных, подтверждённых на практике случая. Список легко расширить:
каждое правило — функция вида fix(lines) -> (new_lines, hits), где hits —
список текстовых описаний для журнала; добавить новое правило — значит
дописать такую функцию и одну строчку в FIX_RULES ниже.
"""

import os
import re

_RE_UNESCAPED_QUOTE = re.compile(r'(?<!\\)"')


def _looks_like_odd_quotes(code):
    """Грубая эвристика: нечётное количество незаэкранированных кавычек
    в строке значит, что мы, вероятно, находимся внутри/у границы
    многострочной строки — трогать такие строки нельзя (двоеточие внутри
    текста — это текст, а не синтаксис)."""
    return len(_RE_UNESCAPED_QUOTE.findall(code)) % 2 == 1


def _indent_len(code):
    return len(code) - len(code.lstrip(" \t"))


def fix_empty_block_colon(lines):
    """Правило 1, см. описание модуля. lines — список строк файла (с
    переносами строк на конце, как из readlines()). Возвращает
    (новый_список_строк, hits)."""
    out = list(lines)
    hits = []
    n = len(out)
    in_string = False
    for i in range(n):
        raw = out[i]
        stripped = raw.rstrip("\r\n")
        code = stripped.rstrip()

        if in_string:
            if _looks_like_odd_quotes(code):
                in_string = False
            continue
        if not code or code.lstrip().startswith("#"):
            continue
        if _looks_like_odd_quotes(code):
            # Многострочная строка начинается на этой строке — пропускаем
            # её и все следующие, пока не встретится закрывающая кавычка.
            in_string = True
            continue
        if not code.endswith(":"):
            continue

        cur_indent = _indent_len(code)
        j = i + 1
        nxt = ""
        while j < n:
            candidate = out[j].rstrip("\r\n")
            if candidate.strip() and not candidate.lstrip().startswith("#"):
                nxt = candidate
                break
            j += 1
        has_block = bool(nxt) and _indent_len(nxt) > cur_indent
        if has_block:
            continue

        eol = raw[len(stripped):]
        new_code = code[:-1].rstrip()
        out[i] = new_code + eol
        hits.append(
            "строка {0}: убрано висящее двоеточие без блока — было: {1!r}"
            .format(i + 1, code.strip())
        )
    return out, hits


_KEYWORDS_NEED_VALUE = (
    "action", "selected", "sensitive", "hovered", "unhovered",
    "alternate", "activate_sound", "keysym", "focus_mask",
)
_RE_DANGLING_KEYWORD = re.compile(
    r'\b(' + "|".join(_KEYWORDS_NEED_VALUE) + r')([ \t]+)#(?=[\[\("\'A-Za-z0-9_])'
)


def fix_dangling_keyword_comment(lines):
    """Правило 2, см. описание модуля. Возвращает (новый_список_строк, hits)."""
    out = list(lines)
    hits = []
    for i, raw in enumerate(out):
        stripped = raw.rstrip("\r\n")
        if stripped.lstrip().startswith("#"):
            continue
        m = _RE_DANGLING_KEYWORD.search(stripped)
        if not m:
            continue
        eol = raw[len(stripped):]
        hash_pos = m.end(2)
        new_code = stripped[:hash_pos] + stripped[hash_pos + 1:]
        out[i] = new_code + eol
        hits.append(
            "строка {0}: убран лишний \"#\" сразу после ключевого слова "
            "\"{1}\" — было: {2!r}".format(i + 1, m.group(1), stripped.strip())
        )
    return out, hits


# (название для журнала, функция, нужна_ли_проверка_глазами)
FIX_RULES = [
    ("пустой блок после двоеточия", fix_empty_block_colon, False),
    ("аргумент без значения (закомментирован unrpyc)", fix_dangling_keyword_comment, True),
]


def _iter_rpy_files(game_dir):
    for root, dirs, files in os.walk(game_dir):
        # game/tl (файлы перевода) не трогаем — там совсем другая
        # структура (old/new, диалоги), эти правила к ней не относятся.
        dirs[:] = [d for d in dirs if d.lower() != "tl"]
        for name in files:
            if name.lower().endswith(".rpy"):
                yield os.path.join(root, name)


def scan_and_fix(game_dir, log=None):
    """Проходит по всем *.rpy в game_dir (кроме game/tl) и применяет все
    правила из FIX_RULES, переписывая изменённые файлы на диске. Каждое
    конкретное исправление построчно пишется в log(). Возвращает
    {'files_changed': N, 'fixes': {название_правила: количество}}."""
    log = log or (lambda msg: None)
    stats = {"files_changed": 0, "fixes": {name: 0 for name, _fn, _review in FIX_RULES}}

    for path in sorted(_iter_rpy_files(game_dir)):
        try:
            with open(path, "r", encoding="utf-8", newline="") as f:
                lines = f.readlines()
        except Exception as e:
            log("  ОШИБКА чтения {0}: {1}".format(path, e))
            continue

        rel = os.path.relpath(path, game_dir)
        changed = False
        for rule_name, fn, needs_review in FIX_RULES:
            lines, hits = fn(lines)
            if not hits:
                continue
            changed = True
            stats["fixes"][rule_name] += len(hits)
            marker = " [ТРЕБУЕТ ПРОВЕРКИ ГЛАЗАМИ]" if needs_review else ""
            log("Исправлено в {0} — {1}{2}:".format(rel, rule_name, marker))
            for h in hits:
                log("    " + h)

        if changed:
            try:
                with open(path, "w", encoding="utf-8", newline="") as f:
                    f.writelines(lines)
            except Exception as e:
                log("  ОШИБКА записи {0}: {1}".format(path, e))
                continue
            stats["files_changed"] += 1

    return stats
