# -*- coding: utf-8 -*-
"""
Точечное исправление известных ошибок, которые вносит unrpyc (ветка
master, нацеленная на Ren'Py 8) при раскомпиляции игр на Ren'Py 7 и ниже.
unrpyc сам честно предупреждает об этом ("this .rpyc file was generated by
ren'py version 7 or below... errors or incorrect decompilation might
occur") — в подавляющем большинстве случаев результат всё равно рабочий,
но иногда проскакивают единичные синтаксические ошибки, из-за которых
Ren'Py SDK падает при генерации файлов перевода (команда "translate").

История подхода (важно, если снова захочется "починить всё сразу"):
первая версия этого модуля сканировала ЦЕЛИКОМ каждый декомпилированный
.rpy файл в поисках подозрительных мест (двоеточие без блока и т.п.) — на
игре с большим количеством таких ошибок это привело к тому, что скрипт
чинил в 3-4 раза больше мест, чем было на самом деле сломано: часть
"висящих двоеточий" на самом деле были частью настоящего ATL-блока,
который декомпилятор просто сдвинул по отступу, а не выдумкой с нуля, и
слепое удаление двоеточия там ломало то, что раньше работало.

Вместо этого теперь модуль работает ТОЧЕЧНО: источник истины — сам
Ren'Py SDK. Когда он падает при команде "translate", он сам совершенно
точно называет каждое проблемное место (файл + номер строки), потому что
пытался это место разобрать по-настоящему. parse_renpy_error_locations()
разбирает такие сообщения из сырого вывода SDK, а apply_fix_at_line()
пытается починить ТОЛЬКО эту одну конкретную строку, не трогая ничего
вокруг — так его "починка" не может задеть код, который и так был в
порядке. Вызывающий код (GUI, см. _generate_tl_worker) организует вокруг
этого повторные запуски SDK и удаление строк, которые чинить не
получилось (см. подробное описание всего цикла в handoff-документе).

Опознаны (по логам пользователя, реальные игры на Ren'Py 7.8.7) два
шаблона поломки:

1) Инструкция заканчивается двоеточием, как будто дальше идёт вложенный
   блок, но блока нет (следующая непустая строка имеет такой же или
   меньший отступ). Ren'Py при этом падает с ошибкой вида "... statement
   expects a non-empty block".
       "show AmyMush:"   (дальше блока нет)
    -> "show AmyMush"

2) В экранном языке (screen language) именованный аргумент (чаще всего
   "action") остаётся без значения, потому что unrpyc не смог до конца
   восстановить исходное Python-выражение и вставил его как комментарий
   сразу после ключевого слова, не убрав само ключевое слово. Ren'Py
   падает с "the X keyword argument was not given a value".
       'textbutton _("Next Page") action #[SetVariable(...), ...]'
    -> 'textbutton _("Next Page") action [SetVariable(...), ...]'

Список правил легко расширить новыми подтверждёнными на практике
случаями — см. apply_fix_at_line().
"""

import re

_RE_UNESCAPED_QUOTE = re.compile(r'(?<!\\)"')
_RE_ERROR_LOCATION = re.compile(r'^File "(?P<file>.+)", line (?P<line>\d+): (?P<msg>.+)$')

_KEYWORDS_NEED_VALUE = (
    "action", "selected", "sensitive", "hovered", "unhovered",
    "alternate", "activate_sound", "keysym", "focus_mask",
)
_RE_DANGLING_KEYWORD = re.compile(
    r'\b(' + "|".join(_KEYWORDS_NEED_VALUE) + r')([ \t]+)#(?=[\[\("\'A-Za-z0-9_])'
)


def _looks_like_odd_quotes(code):
    """Грубая эвристика: нечётное количество незаэкранированных кавычек
    в строке значит, что мы, вероятно, внутри/на границе многострочной
    строки — трогать такую строку нельзя (двоеточие внутри текста — это
    текст, а не синтаксис)."""
    return len(_RE_UNESCAPED_QUOTE.findall(code)) % 2 == 1


def _indent_len(code):
    return len(code) - len(code.lstrip(" \t"))


def parse_renpy_error_locations(output_lines):
    """Разбирает сырой построчный вывод Ren'Py SDK (команда "translate")
    и находит все места ошибок парсера вида:
        File "game/Alchemist.rpy", line 899: show statement expects a non-empty block.
    Возвращает список dict {'file': 'game/Alchemist.rpy' (как сообщил сам
    Ren'Py, путь относительно папки проекта, разделитель "/"), 'line':
    899, 'message': 'show statement expects a non-empty block.'} — в
    порядке появления, без дублей по паре (file, line)."""
    seen = set()
    result = []
    for raw in output_lines:
        m = _RE_ERROR_LOCATION.match(raw.strip())
        if not m:
            continue
        file_rel = m.group("file").replace("\\", "/")
        line_no = int(m.group("line"))
        key = (file_rel, line_no)
        if key in seen:
            continue
        seen.add(key)
        result.append({"file": file_rel, "line": line_no, "message": m.group("msg")})
    return result


def apply_fix_at_line(lines, line_no):
    """Пытается починить ОДНУ конкретную строку (line_no, отсчёт с 1) в
    lines (список строк файла с переносами на конце, как из readlines()).
    Пробует оба известных правила по очереди — какое подойдёт, то и
    применяется. Возвращает (новый_список_строк, описание) при успехе,
    либо (lines_без_изменений, None), если ни одно правило не подошло
    (значит, эта конкретная поломка ещё не опознана — придётся чинить
    руками)."""
    idx = line_no - 1
    if idx < 0 or idx >= len(lines):
        return lines, None

    raw = lines[idx]
    stripped = raw.rstrip("\r\n")
    code = stripped.rstrip()
    eol = raw[len(stripped):]

    # --- Правило 1: висящее двоеточие без блока -------------------------
    if (code and not code.lstrip().startswith("#") and code.endswith(":")
            and not _looks_like_odd_quotes(code)):
        cur_indent = _indent_len(code)
        nxt = ""
        j = idx + 1
        while j < len(lines):
            candidate = lines[j].rstrip("\r\n")
            if candidate.strip() and not candidate.lstrip().startswith("#"):
                nxt = candidate
                break
            j += 1
        has_block = bool(nxt) and _indent_len(nxt) > cur_indent
        if not has_block:
            new_lines = list(lines)
            new_code = code[:-1].rstrip()
            new_lines[idx] = new_code + eol
            return new_lines, "убрано висящее двоеточие без блока — было: {0!r}".format(code.strip())

    # --- Правило 2: аргумент без значения (закомментирован unrpyc) ------
    m = _RE_DANGLING_KEYWORD.search(stripped)
    if m:
        hash_pos = m.end(2)
        new_code = stripped[:hash_pos] + stripped[hash_pos + 1:]
        new_lines = list(lines)
        new_lines[idx] = new_code + eol
        return new_lines, (
            "убран лишний \"#\" сразу после ключевого слова \"{0}\" — было: {1!r}"
            .format(m.group(1), stripped.strip())
        )

    return lines, None


def delete_line(lines, line_no):
    """Удаляет строку line_no (отсчёт с 1) целиком. Возвращает
    (новый_список_строк, удалённый_текст_без_переноса) либо (lines, None),
    если номер строки вне диапазона."""
    idx = line_no - 1
    if idx < 0 or idx >= len(lines):
        return lines, None
    new_lines = list(lines)
    removed = new_lines[idx].rstrip("\r\n")
    del new_lines[idx]
    return new_lines, removed
